### ISSUE TITLE
Node Name Change Not Reaching New World Map

### ISSUE THREAD

**Issue by K5RA** [aredn/worldmap#1]
A node name change on our local mesh has not been picked up in the last three releases of New Map.  
 A node name was changed, and that change was picked up in the hub node's Mesh Status.  The new name was not legitimate, so appeared grayed out in the hub's Mesh Status on the Map.  The bad node name was revised about 1900 local time 20240913 but was not picked up on the 2200, 0400, or 1000 Maps. 
Hub node is KI5ZSF-hAP1, bad node name was GRACES... , corrected node name is KI5ZSF-OEM1.  It's almost like the hub node's Mesh Status is frozen with the bad node name.

**Comment by K5RA** [comment]
Issue still exists.  I checked KI5ZSF-hAP1 Neighbor list.  No "GRACES..." but includes KI5ZSF-OEM1.  On the World Map today (20240915 0450R) the list under KI5ZSF-hAP1 shows GRACES... (but grayed out) and does not have KI5ZSF-OEM1.

**Comment by aanon4** [comment]
Just for context, the worldmap has nothing to do with the firmware for nodes, so fixes here and fixes there will be unrelated.

In this case, a firewall change hadn't persisted across a reboot, which stopped the mapper from mapping. This has now been fixed and I re-ran the mapper by hand.

**Comment by K5RA** [comment]
@aanon4 -  I've watched your work in aredn/aredn, actually opening the PRs and seeing your changes.  You are amazing!  Thank you for all you do for  us. -K5RA

**Comment by K5RA** [comment]
20240915 -  Both 1500R and 1600R AREDN World Maps look good for us.
